### ISSUE TITLE
Missing libpugixml-dev dependency (Debian/Ubuntu)

### ISSUE THREAD

**Issue by zothar** [worldforge/hammer#15]
I'm building on Ubuntu 18.04.3 LTS and encountered an error during the "./hammer.sh install-deps all" step:

.../hammer/work/source/ogre-1.12.4/PlugIns/DotScene/src/DotSceneLoader.cpp:8:10: fatal error: pugixml.hpp: No such file or directory

I corrected the error by installing the libpugixml-dev package.  I've confirmed that it is mentioned neither in the list for Ubuntu at:

https://github.com/worldforge/hammer/blob/master/README.md

no in the list for Debian or Ubuntu at:

https://wiki.worldforge.org/wiki/Hammer_Script

I don't know how much time I'll spend on Worldforge, but I might at some point submit a PR to fix the README.md and request a wiki account to fix the wiki article myself; for now, this issue can serve both to inform the project and perhaps anyone else that runs into this issue.

**Comment by erikogenvik** [comment]
Thanks for the nice description, I've updated both on the wiki and in the script.
