### ISSUE TITLE
script fails on Fedora 36

### ISSUE THREAD

**Issue by ThePowerTool** [worldforge/hammer#16]
Hi! I'm very excited to play with WorldForge.  I found the instructions on https://wiki.worldforge.org/wiki/Hammer_Script and followed them.  I am in the process of reviewing to see if I missed something important making me the cause of the failure.

That said, I captured the process I followed (including the commands I entered in following the instructions) and have a PasteBin that shows everything leading up to the compile failing with errors and not building binaries.
https://pastebin.com/xykgEEtA

I am working on a VM and plan on running though the full install a few times--my goal is to move the server to a headless system for testing, play, and evaluation.

Any help on how to get past where I am stuck would be greatly appreciated.  I will look (I just remembered reading) for logs the script creates (if I remember correctly) to see if there is any additional detail I can share and use for troubleshooting.

Thank you very much!

**Comment by erikogenvik** [comment]
You are missing development libraries for both "boost" and "xdg-basedir". These should be available for Fedora.
An alternative to using the Hammer script is to instead build with Conan, as described here: https://github.com/worldforge/ember#installation

**Comment by ThePowerTool** [comment]
Here's what I have:

]# rpm -qa | grep -i boost
boost-1.76.0-12.fc36.x86_64
boost-atomic-1.76.0-12.fc36.x86_64
boost-chrono-1.76.0-12.fc36.x86_64
boost-container-1.76.0-12.fc36.x86_64
boost-context-1.76.0-12.fc36.x86_64
boost-contract-1.76.0-12.fc36.x86_64
boost-coroutine-1.76.0-12.fc36.x86_64
boost-date-time-1.76.0-12.fc36.x86_64
boost-devel-1.76.0-12.fc36.x86_64
boost-fiber-1.76.0-12.fc36.x86_64
boost-filesystem-1.76.0-12.fc36.x86_64
boost-graph-1.76.0-12.fc36.x86_64
boost-iostreams-1.76.0-12.fc36.x86_64
boost-json-1.76.0-12.fc36.x86_64
boost-locale-1.76.0-12.fc36.x86_64
boost-log-1.76.0-12.fc36.x86_64
boost-math-1.76.0-12.fc36.x86_64
boost-nowide-1.76.0-12.fc36.x86_64
boost-numpy3-1.76.0-12.fc36.x86_64
boost-program-options-1.76.0-12.fc36.x86_64
boost-python3-1.76.0-12.fc36.x86_64
boost-random-1.76.0-12.fc36.x86_64
boost-regex-1.76.0-12.fc36.x86_64
boost-serialization-1.76.0-12.fc36.x86_64
boost-stacktrace-1.76.0-12.fc36.x86_64
boost-system-1.76.0-12.fc36.x86_64
boost-test-1.76.0-12.fc36.x86_64
boost-thread-1.76.0-12.fc36.x86_64
boost-timer-1.76.0-12.fc36.x86_64
boost-type_erasure-1.76.0-12.fc36.x86_64
boost-wave-1.76.0-12.fc36.x86_64
ibus-typing-booster-2.22.1-1.fc36.noarch

]# rpm -qa | grep -i xdg
libxdg-basedir-1.2.0-27.fc36.x86_64
python3-pyxdg-0.27-4.fc36.noarch
xdg-dbus-proxy-0.1.3-1.fc36.x86_64
xdg-desktop-portal-1.12.6-1.fc36.x86_64
xdg-desktop-portal-gnome-42.3-1.fc36.x86_64
xdg-desktop-portal-gtk-1.12.0-5.fc36.x86_64
xdg-user-dirs-0.17-10.fc36.x86_64
xdg-user-dirs-gtk-0.10-22.fc36.x86_64
xdg-utils-1.1.3-11.fc36.noarch

I'm looking at the link to conan you provided and ran into a problem (making me feel really stupid):

[root@fedora ~]# cd /home/cyphesis/
[root@fedora cyphesis]# conan remote add worldforge https://artifactory.ogenvik.org/artifactory/api/conan/conan
[root@fedora cyphesis]# mkdir build && cd build
[root@fedora build]# pwd
/home/cyphesis/build
[root@fedora build]# conan install .. --build missing
ERROR: Conanfile not found at /home/cyphesis/conanfile.txt

True to the error, the file isn't there.  Or anywhere.  I tried running the initial remote add command again but received an error stating "duplicate" and then just to pile-on I blindly added the "-force" option to the end of the command hoping it would create the missing file but no luck.

**Comment by erikogenvik** [comment]
There should be a "boost-devel" package. See https://packages.fedoraproject.org/pkgs/boost/boost-devel/

If you have checked out the code from git you should have the conanfile. Normally you wouldn't checkout the code directly into your home directory though.

**Comment by ThePowerTool** [comment]
Hi, and thank you for your help!

From the listing I provided (above):
boost-devel-1.76.0-12.fc36.x86_64

I downloaded tarballs from the above-referenced WorldForge url (for files/tarballs).

For my attempt using hammer I used hammer and that's all in:
/home/cyphesis/git/WorldForge

So, taking the hint I cd to /home/cyphesis/git/WorldForge/cyphesis and ran:
 mkdir build && cd build

ERROR: The default build profile '/root/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>'

] conan profile detect

] conan install .. --build missing

ERROR: Error while parsing [options] in conanfile.txt
Options should be specified as 'pkg/*:option=value'

updated conanfile [options]:
[options]
pkg/cpython:with_curses=False
#cpython:with_sqlite3=False #Got build errors in the CPython recipe
pkg/cpython:with_tkinter=False
pkg/cpython:with_gdbm=False

] conan install .. --build missing

Graph root
    conanfile.txt: /home/cyphesis/git/WorldForge/cyphesis/conanfile.txt
Requirements
    boost/1.81.0#8dcd9d9df9e0d320714b83cceddbe120 - Downloaded (conancenter)
    bullet3/2.89#fb848ece2a6d6730043cd60d708e070c - Downloaded (conancenter)
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Downloaded (conancenter)
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c - Downloaded (conancenter)
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Downloaded (conancenter)
Build requirements
    b2/4.9.3#5445210661950ce568cfd76158d9e117 - Downloaded (conancenter)
*********************************************************
Recipe 'atlas/0.7.0@worldforge/testing' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'atlas/0.7.0@worldforge/testing' not resolved: atlas/0.7.0@worldforge/testing: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/atlasa9b71eaeac146/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/atlasa9b71eaeac146/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/atlasa9b71eaeac146/e/conanfile.py", line 1, in <module>
    from conans import ConanFile, CMake
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)

I am reviewing and researching this and, as always, any hints would be appreciated! :-)

**Comment by ThePowerTool** [comment]
Update:  I can't believe I'm making what might be progress.  I'm going to document what I do so if I create problems they are exposed.

Researching the above issue:
Recipe 'atlas/0.7.0@worldforge/testing' seems broken.
It is possible that this recipe is not Conan 2.0 ready
 . That specifies:
/root/.conan2/p/atlasa9b71eaeac146/e/conanfile.py'

I found an excellent article on upgrading [migrating] recipes to conan 2.0 at https://docs.conan.io/1/migrating_to_2.0/recipes.html

In conanfile.py I updated the 1st 5 lines:
`from conan import ConanFile
from conan.tools.cmake import cmake_layout


class AtlasConan(ConanFile):
    def layout(self):
        cmake_layout(self)
    name = "atlas"`

and it worked!!!!!

So now I have:

`======== Computing dependency graph ========
mercator/0.4.0@worldforge/testing: Not found in local cache, looking in remotes...
mercator/0.4.0@worldforge/testing: Checking remote: conancenter
mercator/0.4.0@worldforge/testing: Checking remote: worldforge
Decompressing conan_export.tgz
mercator/0.4.0@worldforge/testing: Downloaded recipe revision cf5292c840b0c1c1396450d65e9abd0e
Graph root
    conanfile.txt: /home/cyphesis/git/WorldForge/cyphesis/conanfile.txt
Requirements
    atlas/0.7.0@worldforge/testing#c43171da543e3998d9768320474cda71 - Cache
    boost/1.81.0#8dcd9d9df9e0d320714b83cceddbe120 - Cache
    bullet3/2.89#fb848ece2a6d6730043cd60d708e070c - Cache
    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Cache
    libbacktrace/cci.20210118#ec1aa63bbc10145c6a299e68e711670c - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    b2/4.9.3#5445210661950ce568cfd76158d9e117 - Cache
*********************************************************
Recipe 'mercator/0.4.0@worldforge/testing' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: Package 'mercator/0.4.0@worldforge/testing' not resolved: mercator/0.4.0@worldforge/testing: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/merca27396a12468c9/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/merca27396a12468c9/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/merca27396a12468c9/e/conanfile.py", line 1, in <module>
    from conans import ConanFile, CMake, tools
ImportError: cannot import name 'ConanFile' from 'conans' (/usr/lib/python3.10/site-packages/conans/__init__.py)`

**Comment by ThePowerTool** [comment]
Update:  On a roll!

updated /root/.conan2/p/merca27396a12468c9/e/conanfile.py
`from conan import ConanFile
from conan.tools.cmake import cmake_layout
from conan.tools.layout import basic_layout
from conan.tools.files import get


class MercatorConan(ConanFile):
    def layout(self):
        cmake_layout(self)
    def layout(self):
        basic_layout(self, src_folder=".")
    def source(self):
        get(self, **self.conan_data["sources"][self.version], strip_root=True)
    name = "mercator"`

That worked!

] conan install .. --build missing
Now shows a similar error for:
/root/.conan2/p/wfmat74894004ce7d2/e/conanfile.py

Cookie-cutter with above update to conanfile.py (for conan 2.0 migration)

Now I'm on to the same issue with:
/root/.conan2/p/varco4c9784a3dbd02/e/conanfile.py

And cookie cutter again!

Moving on to:
/root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py

OK, this one might hurt.  Reading about "generators"

**Comment by ThePowerTool** [comment]
Hi, again!  I think I need some help with /root/.conan2/p/sigc+f79eeab132bc0/e/conanfile.py because it contains MSBuild and according to the migration site
1.  MSBuild has been broken into more detailed and specific "parts" and
2. and I quote:  "This class will require very soon to define both the “host” and “build” profiles. It is very recommended to start defining both profiles immediately to avoid future breaking. Furthermore, some features, like trying to cross-compile might not work at all if the “build” profile is not provided."

Any thoughts or suggestions? :-)

**Comment by ThePowerTool** [comment]
OK, I just realized I followed your suggestion to move to the conan install and I'm documenting this under hammer.  I'm closing this issue.
